# Teacher information - Join
    - Author: Santiago Avella. Git hub: https://github.com/TiagoMimi

In [1]:
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")
# *Configure pandas to display all columns in DataFrame outputs*
pd.set_option('display.max_columns', None)

## Load the data

In [2]:
# Current working directory
script_path = Path.cwd()

# Find the project folder
project_path = script_path

while project_path.name != "saber11_db":
    project_path = project_path.parent

### 2024

In [3]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2024"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (con mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Docentes por jornada según máximo nivel educativo alcanzado y rangos de edad.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, sep=",")

df_escalafon_2024 = dataframes["df_escalafon"]
df_clei_2024 = dataframes["df_clei"]
df_vinculacion_2024 = dataframes["df_vinculacion"]
df_nivel_educativo_2024 = dataframes["df_nivel_educativo"]
df_jornada_edad_2024 = dataframes["df_jornada_edad"]

### 2023

In [4]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2023"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (con mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Docentes por jornada según máximo nivel educativo alcanzado y rangos de edad.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2023 = dataframes["df_escalafon"]
df_clei_2023 = dataframes["df_clei"]
df_vinculacion_2023 = dataframes["df_vinculacion"]
df_nivel_educativo_2023 = dataframes["df_nivel_educativo"]
df_jornada_edad_2023 = dataframes["df_jornada_edad"]

### 2022

In [5]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2022"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (con mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Docentes por jornada según máximo nivel educativo alcanzado y rangos de edad.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2022 = dataframes["df_escalafon"]
df_clei_2022 = dataframes["df_clei"]
df_vinculacion_2022 = dataframes["df_vinculacion"]
df_nivel_educativo_2022 = dataframes["df_nivel_educativo"]
df_jornada_edad_2022 = dataframes["df_jornada_edad"]

### 2021

In [6]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2021"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2021 = dataframes["df_escalafon"]
df_clei_2021 = dataframes["df_clei"]
df_vinculacion_2021 = dataframes["df_vinculacion"]
df_nivel_educativo_2021 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2021 = dataframes["df_asignacion_academica"]
df_jornada_edad_2021 = dataframes["df_jornada_edad"]

### 2020

In [7]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2020"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]
# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=";")

df_escalafon_2020 = dataframes["df_escalafon"]
df_clei_2020 = dataframes["df_clei"]
df_vinculacion_2020 = dataframes["df_vinculacion"]
df_nivel_educativo_2020 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2020 = dataframes["df_asignacion_academica"]
df_jornada_edad_2020 = dataframes["df_jornada_edad"]

### 2019

In [8]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2019"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]
# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=";")

df_escalafon_2019 = dataframes["df_escalafon"]
df_clei_2019 = dataframes["df_clei"]
df_vinculacion_2019 = dataframes["df_vinculacion"]
df_nivel_educativo_2019 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2019 = dataframes["df_asignacion_academica"]
df_jornada_edad_2019 = dataframes["df_jornada_edad"]

### 2018

In [42]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2018"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2018 = dataframes["df_escalafon"]
df_clei_2018 = dataframes["df_clei"]
df_vinculacion_2018 = dataframes["df_vinculacion"]
df_nivel_educativo_2018 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2018 = dataframes["df_asignacion_academica"]
df_jornada_edad_2018 = dataframes["df_jornada_edad"]

### 2017

In [10]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2017"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Último nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.txt",
    data_path / "Último nivel educativo alcanzado por los docente según rangos de edad por jornada.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=";",
                                encoding="latin-1")

df_escalafon_2017 = dataframes["df_escalafon"]
df_clei_2017 = dataframes["df_clei"]
df_vinculacion_2017 = dataframes["df_vinculacion"]
df_nivel_educativo_2017 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2017 = dataframes["df_asignacion_academica"]
df_jornada_edad_2017 = dataframes["df_jornada_edad"]

In [78]:
df_escalafon_2017 = df_escalafon_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})
df_clei_2017 = df_clei_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})
df_vinculacion_2017 = df_vinculacion_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})

### 2016

In [38]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2016"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.txt",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).txt",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.txt",
    data_path / "Docentes ocupados, según carácter, por nivel educativo (educación tradicional) donde tiene la mayor asignación académica.txt",
    data_path / "Último nivel educativo alcanzado por el docente,  nivel educativo donde tiene la mayor asignación académica y rango de edad del docente por jornada.txt",
    data_path / "Último nivel educativo alcanzado por los docentes  con asignación académica y edad del docente.txt"]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each TXT separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(
        file,
        sep="\t",
        encoding="latin-1"
    )

# Assign DataFrames
df_escalafon_2016 = dataframes["df_escalafon"]
df_clei_2016 = dataframes["df_clei"]
df_vinculacion_2016 = dataframes["df_vinculacion"]
df_asignacion_academica_2016 = dataframes["df_asignacion_academica"]
df_nivel_educativo_2016 = dataframes["df_nivel_educativo"]
df_jornada_edad_2016 = dataframes["df_jornada_edad"]

### 2015

In [36]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2015"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados según cáracter, para niveles de enseñanza CLEI y Otros Modelos.csv",
    data_path / "Docentes ocupados en la sede educativa.csv",
    data_path / "Docentes ocupados según cáracter,para los niveles de enseñanza prees, pri,seca y med.csv",
    data_path / "útimo nivel educativo alcanzado por el docente.csv",
    data_path / "Informacion general de docentes por jornada.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2015 = dataframes["df_escalafon"]
df_clei_2015 = dataframes["df_clei"]
df_vinculacion_2015 = dataframes["df_vinculacion"]
df_nivel_educativo_2015 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2015 = dataframes["df_asignacion_academica"]
df_jornada_edad_2015 = dataframes["df_jornada_edad"]

## Concat

#### Escalafon

In [53]:
df_escalafon = pd.concat([df_escalafon_2015,
                        df_escalafon_2016,
                        df_escalafon_2017,
                        df_escalafon_2018,
                        df_escalafon_2019,
                        df_escalafon_2020,
                        df_escalafon_2021,
                        df_escalafon_2022,
                        df_escalafon_2023,
                        df_escalafon_2024], axis=0)

In [80]:
df_escalafon

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,GRADOESCA_ID,GRADOESCA_CODIGO,GRADOESCA_NOMBRE,SEDEDOES_CANTIDAD_HOMBRE,SEDEDOES_CANTIDAD_MUJER
0,308758001975,2,2015,9,7,Grado 7,2,3
1,308758076142,2,2015,15,13,Grado 13,0,1
2,283094000442,2,2015,14,12,Grado 12,0,1
3,315238001464,2,2015,22,2A_SE,Grado 2A Sin especialización,0,1
4,308758001975,2,2015,6,4,Grado 4,0,2
...,...,...,...,...,...,...,...,...
133491,325269004131,11,2024,9,7,Grado 7,0,4
133492,273686000211,11,2024,16,14,Grado 14,0,1
133493,227615061063,11,2024,22,2A_SE,Grado 2A Sin especialización,0,1
133494,252250000242,11,2024,16,14,Grado 14,0,1
133495,252250000242,11,2024,22,2A_SE,Grado 2A Sin especialización,0,1

#### Clei

In [67]:
df_clei = pd.concat([df_clei_2015,
                        df_clei_2016,
                        df_clei_2017,
                        df_clei_2018,
                        df_clei_2019,
                        df_clei_2020,
                        df_clei_2021,
                        df_clei_2022,
                        df_clei_2023,
                        df_clei_2024], axis=0)

In [81]:
df_clei

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,SEDEDONI_CANTIDAD_HOMBRE,SEDEDONI_CANTIDAD_MUJER
0,341298000034,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,6,2
1,386568061022,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,8,3
2,168547000551,2,2015,6,6,Otros modelos educativos para jóvenes y adultos,0,2
3,311001109389,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,9,3
4,308001001676,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,1,2
...,...,...,...,...,...,...,...,...
2013,444001003793,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,0,2
2014,350001007093,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,3,4
2015,311001108684,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,13,10
2016,141001005203,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,0,3
2017,325307800001,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,0,3

#### Vinculacion

In [79]:
df_vinculacion = pd.concat([df_vinculacion_2015,
                        df_vinculacion_2016,
                        df_vinculacion_2017,
                        df_vinculacion_2018,
                        df_vinculacion_2019,
                        df_vinculacion_2020,
                        df_vinculacion_2021,
                        df_vinculacion_2022,
                        df_vinculacion_2023,
                        df_vinculacion_2024], axis=0)

In [82]:
df_vinculacion

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,VINCULA_ID,VINCULA_CODIGO,VINCULA_NOMBRE,SEDEDOC_CANTIDAD_HOMBRE,SEDEDOC_CANTIDAD_MUJER
0,285001001340,2,2015,1,1,"Docentes de planta, con grado en el escalafón",7,7
1,285001001340,2,2015,2,2,"Docentes por contrato, con grado en el escalafón",0,2
2,250223000203,2,2015,1,1,"Docentes de planta, con grado en el escalafón",1,1
3,268101000781,2,2015,1,1,"Docentes de planta, con grado en el escalafón",5,4
4,268101000781,2,2015,2,2,"Docentes por contrato, con grado en el escalafón",1,1
...,...,...,...,...,...,...,...,...
62278,244560000975,11,2024,3,3,"Docentes de planta, sin grado en el escalafón",11,28
62279,244560000975,11,2024,1,1,"Docentes de planta, con grado en el escalafón",0,1
62280,413140000259,11,2024,1,1,"Docentes de planta, con grado en el escalafón",4,2
62281,413140000259,11,2024,2,2,Docentes contrato o canasta educativa (con gra...,3,2
62282,254001003196,11,2024,1,1,"Docentes de planta, con grado en el escalafón",15,18

#### Asignacion academica

In [84]:
df_asignacion_academica_2015

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,250287000223,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,1
1,244001002747,2,2015,1,1,Académico,1,1,Preescolar,16,10,Todas las áreas,0,1
2,244001002747,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,1
3,244560003362,2,2015,1,1,Académico,1,1,Preescolar,16,10,Todas las áreas,1,3
4,244560003362,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,6,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187761,376364002343,2,2015,1,1,Académico,1,1,Preescolar,16,10,Todas las áreas,0,2
187762,376364002343,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,3
187763,215176000658,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,1
187764,286571004764,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,1
187765,225572000500,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,1,0

In [85]:
df_asignacion_academica_2016

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,268468000604,3,2016,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,1
1,368001006841,3,2016,1,1,Académico,2,2,Básica primaria,1,3,Ciencias naturales y educación ambiental,0,1
2,205819000060,3,2016,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,1,1
3,205819000060,3,2016,1,1,Académico,3,3,Básica secundaria,16,2,Todas las áreas,1,0
4,368001006841,3,2016,1,1,Académico,2,2,Básica primaria,2,4,"Ciencias sociales, historia, geografía, consti...",0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191832,173001005351,3,2016,1,1,Académico,1,1,Preescolar,16,2,Todas las áreas,0,2
191833,173001005351,3,2016,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,5,5
191834,173001005351,3,2016,1,1,Académico,3,3,Básica secundaria,16,2,Todas las áreas,4,6
191835,173001005351,3,2016,2,2,Técnico,4,4,Media,12,3,Comercial,4,1
191836,291263000181,3,2016,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,1,0

In [86]:
df_asignacion_academica_2017

,ï»¿SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,199001001681,4,2017,1,1,AcadÃ©mico,2,2,BÃ¡sica primaria,1,3,Ciencias naturales y educaciÃ³n ambiental,0,3
1,199001001681,4,2017,1,1,AcadÃ©mico,2,2,BÃ¡sica primaria,2,4,"Ciencias sociales, historia, geografÃ­a, const...",0,3
2,199001001681,4,2017,1,1,AcadÃ©mico,2,2,BÃ¡sica primaria,3,5,EducaciÃ³n Ã©tica y en valores humanos,0,1
3,199001001681,4,2017,1,1,AcadÃ©mico,1,1,Preescolar,5,7,"Humanidades, lengua castellana",0,1
4,199001001681,4,2017,1,1,AcadÃ©mico,2,2,BÃ¡sica primaria,5,7,"Humanidades, lengua castellana",2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236627,354518001139,4,2017,1,1,AcadÃ©mico,3,3,BÃ¡sica secundaria,9,11,EducaciÃ³n religiosa,1,0
236628,354518001139,4,2017,1,1,AcadÃ©mico,1,1,Preescolar,19,14,Idiomas extranjeros,0,1
236629,354518001139,4,2017,1,1,AcadÃ©mico,2,2,BÃ¡sica primaria,19,14,Idiomas extranjeros,0,1
236630,354518001139,4,2017,1,1,AcadÃ©mico,3,3,BÃ¡sica secundaria,19,14,Idiomas extranjeros,1,0
236631,223555001877,4,2017,1,1,AcadÃ©mico,2,2,BÃ¡sica primaria,16,2,Todas las Ã¡reas,0,1

In [87]:
df_asignacion_academica_2018

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,141349000108,5,2018,1,1,Académico,3,3,Básica secundaria,1,3,Ciencias naturales y educación ambiental,1,1
1,141349000108,5,2018,1,1,Académico,4,4,Media,1,3,Ciencias naturales y educación ambiental,2,1
2,141349000108,5,2018,1,1,Académico,4,4,Media,2,4,"Ciencias sociales, historia, geografía, consti...",4,1
3,141349000108,5,2018,1,1,Académico,3,3,Básica secundaria,3,5,Educación ética y en valores humanos,0,1
4,141349000108,5,2018,1,1,Académico,3,3,Básica secundaria,4,6,Educación artística y cultural,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216205,252696000955,5,2018,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,1
216206,219418001579,5,2018,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,1,0
216207,219418001579,5,2018,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,1,0
216208,281065003081,5,2018,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,1,0
216209,276126000451,5,2018,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,1

In [88]:
df_asignacion_academica_2019

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,311001109028,6,2019,1,1,Académico,2,2,Básica primaria,2,4,"Ciencias sociales, historia, geografía, consti...",0,1
1,311001109028,6,2019,1,1,Académico,2,2,Básica primaria,5,7,"Humanidades, lengua castellana",0,1
2,311001109028,6,2019,1,1,Académico,2,2,Básica primaria,6,8,"Educación física, recreación y deportes",1,0
3,311001109028,6,2019,1,1,Académico,2,2,Básica primaria,7,9,Matemáticas,0,1
4,311001109028,6,2019,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219307,125473000137,6,2019,1,1,Académico,2,2,Básica primaria,19,14,Idiomas extranjeros,1,0
219308,125473000137,6,2019,1,1,Académico,3,3,Básica secundaria,19,14,Idiomas extranjeros,0,5
219309,125473000137,6,2019,1,1,Académico,4,4,Media,19,14,Idiomas extranjeros,0,1
219310,125473000137,6,2019,1,1,Académico,2,2,Básica primaria,43,15,Filosofía,0,1
219311,125473000137,6,2019,2,2,Técnico,4,4,Media,10,1,Industrial,1,1

In [89]:
df_asignacion_academica_2020

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,273067001881,7,2020,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,1
1,105360000121,7,2020,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,0,4
2,163130000149,7,2020,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,5
3,163130000149,7,2020,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,0,1
4,205315000042,7,2020,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219719,219701000376,7,2020,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,0,2
219720,291407000204,7,2020,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,1,0
219721,291407000204,7,2020,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,1,0
219722,291798000025,7,2020,1,1,Académico,2,2,Básica primaria,16,2,Todas las áreas,3,1
219723,291798000025,7,2020,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,1,0

In [90]:
df_asignacion_academica_2021

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,154001008967,8,2021,1,1,Académico,3,3,Básica secundaria,7,9,Matemáticas,2,0
1,154001008967,8,2021,1,1,Académico,3,3,Básica secundaria,5,7,"Humanidades, lengua castellana",0,1
2,154001008967,8,2021,1,1,Académico,3,3,Básica secundaria,6,8,"Educación física, recreación y deportes",1,0
3,176275001393,8,2021,1,1,Académico,3,3,Básica secundaria,1,3,Ciencias naturales y educación ambiental,0,4
4,176275001393,8,2021,1,1,Académico,4,4,Media,1,3,Ciencias naturales y educación ambiental,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259151,308758004087,8,2021,1,1,Académico,4,4,Media,7,9,Matemáticas,0,1
259152,308758004087,8,2021,1,1,Académico,3,3,Básica secundaria,8,10,Tecnología e informática,0,1
259153,308758004087,8,2021,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,0,7
259154,308758004087,8,2021,1,1,Académico,3,3,Básica secundaria,19,14,Idiomas extranjeros,0,1
259155,308758004087,8,2021,1,1,Académico,4,4,Media,42,13,Ciencias Económicas,0,1

In [ ]:
df_asignacion_academica = pd.concat([df_asignacion_academica_2015,
                        df_asignacion_academica_2016,
                        df_asignacion_academica_2017,
                        df_asignacion_academica_2018,
                        df_asignacion_academica_2019,
                        df_asignacion_academica_2020,
                        df_asignacion_academica_2021,
                        df_asignacion_academica_2022,
                        df_asignacion_academica_2023,
                        df_asignacion_academica_2024], axis=0)

#### Nivel educativo

In [94]:
df_nivel_educativo_2015

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,NIVELEDUCDOC_ID,NIVELEDUCDOC_CODIGO,NIVELEDUCDOC_NOMBRE,SEDEDONI_CANTIDAD_HOMBRE,SEDEDONI_CANTIDAD_MUJER
0,347555027974,2,2015,1,1,Preescolar,7,7,Licenciado,0,1
1,347555027974,2,2015,2,2,Básica primaria,7,7,Licenciado,0,5
2,347555027974,2,2015,3,3,Básica secundaria,7,7,Licenciado,0,1
3,347555027974,2,2015,1,1,Preescolar,8,8,Profesional diferente a licenciado,0,2
4,347555027974,2,2015,3,3,Básica secundaria,8,8,Profesional diferente a licenciado,2,0
...,...,...,...,...,...,...,...,...,...,...,...
147052,376364002033,2,2015,1,1,Preescolar,7,7,Licenciado,0,1
147053,376364002033,2,2015,1,1,Preescolar,8,8,Profesional diferente a licenciado,0,1
147054,450568001481,2,2015,2,2,Básica primaria,4,4,Etnoeducador,1,0
147055,976001000125,2,2015,1,1,Preescolar,5,5,Perito experto o técnico en educación,0,2
147056,976001000125,2,2015,1,1,Preescolar,7,7,Licenciado,1,1

In [95]:
df_nivel_educativo_2016

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,JORNADA_ID,JORNADA_CODIGO,JORNADA_NOMBRE,NIVELEDUCDOC_ID,NIVELEDUCDOC_CODIGO,NIVELEDUCDOC_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,RANGODOCENTE_ID,RANDOC_CODIGO,RANDOC_NOMBRE,JORDOC_CANTIDAD_HOMBRE,JORDOC_CANTIDAD_MUJER
0,205034000361,3,2016,1,1,Completa,9,9,Posgrado en educación o programa pedagógico,2,2,Básica primaria,4,EN3135,Entre 31 y 35 años,1,0
1,268327000023,3,2016,2,2,Mañana,1,1,Bachillerato pedagógico,2,2,Básica primaria,6,MAY40,Mayor a 40 años,0,1
2,268327000074,3,2016,2,2,Mañana,9,9,Posgrado en educación o programa pedagógico,2,2,Básica primaria,6,MAY40,Mayor a 40 años,0,2
3,268468000469,3,2016,1,1,Completa,3,3,Normalista superior,2,2,Básica primaria,3,EN2630,Entre 26 y 30 años,0,1
4,268468000124,3,2016,1,1,Completa,3,3,Normalista superior,2,2,Básica primaria,4,EN3135,Entre 31 y 35 años,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207500,227025080682,3,2016,2,2,Mañana,1,1,Bachillerato pedagógico,2,2,Básica primaria,2,EN2025,Entre 20 y 25 años,1,0
207501,227075000574,3,2016,2,2,Mañana,1,1,Bachillerato pedagógico,2,2,Básica primaria,2,EN2025,Entre 20 y 25 años,1,0
207502,273236000121,3,2016,2,2,Mañana,9,9,Posgrado en educación o programa pedagógico,2,2,Básica primaria,6,MAY40,Mayor a 40 años,0,1
207503,283592001782,3,2016,2,2,Mañana,7,7,Licenciado,2,2,Básica primaria,3,EN2630,Entre 26 y 30 años,0,1
207504,218592000470,3,2016,2,2,Mañana,3,3,Normalista superior,2,2,Básica primaria,4,EN3135,Entre 31 y 35 años,0,1

#### edad