# Result Info - Translation
    - Author: Santiago Avella. Git hub: https://github.com/TiagoMimi

In [52]:
import pandas as pd
from pathlib import Path
import json
# *Configure pandas to display all columns in DataFrame outputs*
pd.set_option('display.max_columns', None)

# Load data

In [53]:
# Current working directory
script_path = Path.cwd()

# Find the project folder
project_path = script_path

while project_path.name != "github":
    project_path = project_path.parent

In [54]:
data_path = project_path / "saber11_db" / "data" / "joined" 

# Read student data types
with open(
    data_path / "data_types_student.json",
    "r",
    encoding="utf-8"
) as file:
    data_type_student = json.load(file)


# List of CSV files
file_list = [
    data_path / "result_info.csv"
]

# DataFrame names
df_names = [
    "df_result_info"]


# Read CSV files using the data types stored in the JSON files
dataframes = {}

for name, file in zip(df_names, file_list):

    # Get table name
    table_name = name.replace("df_", "")

    # Select the corresponding data type dictionary
    if table_name.startswith("student_"):
        dtype_mapping = data_type_student[table_name]
    else:
        dtype_mapping = data_type_student[table_name]

    # Read CSV
    dataframes[name] = pd.read_csv(
        file,
        sep=";",
        dtype=dtype_mapping,
        low_memory=False
    )


# Assign DataFrames
df_result_info = dataframes["df_result_info"]

### Def for translation

In [55]:
def translate_values_dictionary(df,column,dict_translation):
    
    df[column] = df[column].replace(dict_translation)

    return df

# Result_info

#### student_id => STUDENT_ID

- Id público del inscrito (SB11)
- Public Identifier of the Enrolled Student (SB11)

In [56]:
df_result_info = df_result_info.rename(columns={"student_id":"STUDENT_ID"})

#### school_institution_id => SCHOOL_INSTITUTION_ID

- Código Dane del Establecimiento Educativo 
- Educational Institution DANE ID (DANE (National Administrative Department of Statistics): Colombia's official statistical agency responsible for producing and disseminating statistical information about the country's demographic, social, economic, and educational conditions.)

In [57]:
df_result_info = df_result_info.rename(columns={"school_institution_id":"SCHOOL_INSTITUTION_ID"})

#### school_campus_id => SCHOOL_CAMPUS_ID

- Código Dane de la Sede
- DANE ID of the Campus (DANE (National Administrative Department of Statistics): Colombia's official statistical agency responsible for producing and disseminating statistical information about the country's demographic, social, economic, and educational conditions.)

In [58]:
df_result_info = df_result_info.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### desemp_ingles,	desemp_lectura_critica,	desemp_matematicas,	desemp_sociales_ciudadanas, desemp_c_naturales => Delete

- Desempeño en: Inglés, lectura crítica, matemáticas, ciencias sociales y ciudadanas, ciencias naturales.
- Performance on: English, critical reading, natural science ,math, social and citizen sciences.

In [59]:
df_result_info = df_result_info.drop(columns={"desemp_ingles",
                                                "desemp_lectura_critica",
                                                "desemp_matematicas",
                                                "desemp_sociales_ciudadanas",
                                                "desemp_c_naturales"})

#### estu_depto_presentacion => STUDENT_DEPART_TEST_TAKEN

- Departamento de presentación del examen
- Deparment where the test was taken

In [60]:
df_result_info = df_result_info.rename(columns={"estu_depto_presentacion":"STUDENT_DEPART_TEST_TAKEN"})

In [61]:
dict_translation = {
    "BOGOTÁ": "bogota",
    "ANTIOQUIA": "antioquia",
    "VALLE": "valle_cauca",
    "CUNDINAMARCA": "cundinamarca",
    "ATLANTICO": "atlantico",
    "BOLIVAR": "bolivar",
    "SANTANDER": "santander",
    "CORDOBA": "cordoba",
    "NARIÑO": "narino",
    "TOLIMA": "tolima",
    "BOYACA": "boyaca",
    "MAGDALENA": "magdalena",
    "NORTE SANTANDER": "norte_santander",
    "CAUCA": "cauca",
    "HUILA": "huila",
    "CESAR": "cesar",
    "META": "meta",
    "SUCRE": "sucre",
    "CALDAS": "caldas",
    "RISARALDA": "risaralda",
    "BOGOTA": "bogota",
    "LA GUAJIRA": "la_guajira",
    "QUINDIO": "quindio",
    "CASANARE": "casanare",
    "CHOCO": "choco",
    "CAQUETA": "caqueta",
    "PUTUMAYO": "putumayo",
    "ARAUCA": "arauca",
    "GUAVIARE": "guaviare",
    "AMAZONAS": "amazonas",
    "SAN ANDRES": "san_andres",
    "VICHADA": "vichada",
    "VAUPES": "vaupes",
    "GUAINIA": "guainia",
    "EXTRANJERO": "foreign"
}

In [62]:
df_student_info = translate_values_dictionary(df_result_info,
                                "STUDENT_DEPART_TEST_TAKEN",
                                dict_translation)

In [63]:
df_result_info["STUDENT_DEPART_TEST_TAKEN"].value_counts()

STUDENT_DEPART_TEST_TAKEN
bogota             901043
antioquia          751780
valle_cauca        467170
cundinamarca       364473
atlantico          329537
santander          264259
bolivar            254939
cordoba            207482
narino             175429
boyaca             170369
tolima             166935
magdalena          165476
norte_santander    165380
cauca              146589
huila              140297
cesar              137366
meta               124224
caldas             112482
sucre              111112
risaralda          104481
la_guajira          89946
quindio             64268
casanare            60439
choco               46178
caqueta             43059
putumayo            42800
arauca              34173
guaviare            10666
amazonas             8489
san_andres           6499
vichada              5726
vaupes               3948
guainia              3317
Name: count, dtype: int64

#### estu_cod_depto_presentacion => DELETE

- ID del departamento de presentación del examen
- Department ID where the exam was taken

In [64]:
df_result_info = df_result_info.drop(columns={"estu_cod_depto_presentacion"})

#### estu_cod_mcpio_presentacion => STUDENT_ID_MUNICI_TEST_TAKEN

- ID del Municipio de presentación del examen
- Municipality ID where the exam was taken

In [65]:
df_result_info = df_result_info.rename(columns={"estu_cod_mcpio_presentacion": "STUDENT_ID_MUNICI_TEST_TAKEN"})

#### estu_mcpio_presentacio => STUDENT_MUNICI_TEST_TAKEN

- Municipio de presentación del examen
- Municipality where the exam was taken

In [66]:
df_result_info = df_result_info.rename(columns={"estu_mcpio_presentacion": "STUDENT_MUNICI_TEST_TAKEN"})

In [67]:
import unicodedata

df_result_info["STUDENT_MUNICI_TEST_TAKEN"] = (
    df_result_info["STUDENT_MUNICI_TEST_TAKEN"]
    .apply(lambda x: ''.join(
        c for c in unicodedata.normalize('NFD', str(x))
        if unicodedata.category(c) != 'Mn'
    ).lower().replace(' ', '_'))
)

In [68]:
df_result_info

,STUDENT_ID,SCHOOL_INSTITUTION_ID,SCHOOL_CAMPUS_ID,STUDENT_ID_MUNICI_TEST_TAKEN,STUDENT_DEPART_TEST_TAKEN,STUDENT_MUNICI_TEST_TAKEN,percentil_c_naturales,percentil_global,percentil_ingles,percentil_lectura_critica,percentil_matematicas,percentil_sociales_ciudadanas,periodo,punt_c_naturales,punt_global,punt_ingles,punt_lectura_critica,punt_matematicas,punt_sociales_ciudadanas
0,SB11201510000485,311769000921,311769000921,11001,bogota,bogota_d.c.,NaN,NaN,NaN,NaN,NaN,NaN,20151,69,347,90.0,64,72,66
1,SB11201510115564,376250000871,376250000871,76622,valle_cauca,roldanillo,NaN,NaN,NaN,NaN,NaN,NaN,20151,48,239,45.0,49,48,47
2,SB11201510097089,311001105928,311001105928,11001,bogota,bogota_d.c.,NaN,NaN,NaN,NaN,NaN,NaN,20151,34,166,41.0,18,43,35
3,SB11201510115560,376250000871,376250000871,76622,valle_cauca,roldanillo,NaN,NaN,NaN,NaN,NaN,NaN,20151,34,183,42.0,51,29,31
4,SB11201510002784,308001004209,308001004209,8001,atlantico,barranquilla,NaN,NaN,NaN,NaN,NaN,NaN,20151,69,351,85.0,61,82,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5681671,SB11202430031940,111001012963,111001012963,11001,bogota,bogota_d.c.,74.0,64.0,87.0,75.0,10.0,84.0,20242,58,276,66.0,61,36,62
5681672,SB11202430002696,320001006881,320001006881,20001,cesar,valledupar,6.0,23.0,37.0,55.0,20.0,27.0,20242,35,215,46.0,55,41,40
5681673,SB11202430070974,176520002520,176520800222,76520,valle_cauca,palmira,34.0,47.0,66.0,78.0,43.0,34.0,20242,45,251,55.0,62,50,42
5681674,SB11202430586516,305001020558,305001020558,5001,antioquia,medellin,10.0,3.0,8.0,5.0,5.0,3.0,20242,37,165,35.0,35,31,28
5681675,SB11202430450964,141001001593,141001001593,41001,huila,neiva,78.0,63.0,83.0,53.0,25.0,77.0,20242,59,274,64.0,55,43,59

#### percentil_c_naturales => PERCENTILE_NATURAL_SCIENCE

- Percentil en ciencias naturales
- Percentile on Natural Science

In [69]:
df_result_info = df_result_info.rename(columns={"percentil_c_naturales":"PERCENTILE_NATURAL_SCIENCE"})

#### percentil_ingles	 => PERCENTILE_ENGLISH

- Percentil en Inglés
- Percentile on English

In [70]:
df_result_info = df_result_info.rename(columns={"percentil_ingles":"PERCENTILE_ENGLISH"})

#### percentil_lectura_critica => PERCENTILE_CRITICAL_READING

- Percentil en Lectura critica
- Percentile on Critical reading

In [71]:
df_result_info = df_result_info.rename(columns={"percentil_lectura_critica":"PERCENTILE_CRITICAL_READING"})

#### percentil_matematicas	 => PERCENTILE_MATH

- Percentil en matemáticas
- Percentile on Math

In [72]:
df_result_info = df_result_info.rename(columns={"percentil_matematicas":"PERCENTILE_MATH"})

#### percentil_sociales_ciudadanas	 => PERCENTILE_SOCIAL_CITIZEN

- Percentil en ciencias sociales y ciudadanas
- Percentile on social and citizen sciences

In [73]:
df_result_info = df_result_info.rename(columns={"percentil_sociales_ciudadanas":"PERCENTILE_SOCIAL_CITIZEN"})

#### percentil_global => PERCENTILE_TOTAL_SCORE

- Percentil de la puntuación global
- Overall Percentile reached by the student

In [74]:
df_result_info = df_result_info.rename(columns={"percentil_global":"PERCENTILE_TOTAL_SCORE"})

#### periodo => YEAR_PERIOD_TEST_TAKEN

- Año y perido (1 ó 2) en que se presento la prueba.
- Year and period when the test was taken (1 or 2).

In [75]:
df_result_info = df_result_info.rename(columns={"periodo":"YEAR_PERIOD_TEST_TAKEN"})

#### punt_c_naturales => SCORE_NATURAL_SCIENCE

- Puntaje en ciencias naturales
- Score on Natural Science

In [76]:
df_result_info = df_result_info.rename(columns={"punt_c_naturales":"SCORE_NATURAL_SCIENCE"})

#### punt_ingles => SCORE_NENGLISH

- Puntaje en Inglés
- Score on English

In [78]:
df_result_info = df_result_info.rename(columns={"punt_ingles":"SCORE_ENGLISH"})

#### punt_lectura_critica => SCORE_CRITICAL_READING

- Puntaje en lectura critica
- Score on Critical Reading

In [80]:
df_result_info = df_result_info.rename(columns={"punt_lectura_critica":"SCORE_CRITICAL_READING"})

#### punt_matematicas => SCORE_MATH

- Puntaje en matemáticas
- Score on Math

In [82]:
df_result_info = df_result_info.rename(columns={"punt_matematicas":"SCORE_MATH"})

#### punt_sociales_ciudadanas => SCORE_SOCIAL_CITIZEN

- Puntaje en ciencias sociales y ciudadanas
- Score on social and citizen science

In [84]:
df_result_info = df_result_info.rename(columns={"punt_sociales_ciudadanas":"SCORE_SOCIAL_CITIZEN"})

#### punt_global => SCORE_TOTAL

- Puntaje total obtenido en la prueba
- Total score

In [ ]:
df_result_info = df_result_info.rename(columns={"punt_sociales_ciudadanas":"SCORE_SOCIAL_CITIZEN"})

In [85]:
df_result_info

,STUDENT_ID,SCHOOL_INSTITUTION_ID,SCHOOL_CAMPUS_ID,STUDENT_ID_MUNICI_TEST_TAKEN,STUDENT_DEPART_TEST_TAKEN,STUDENT_MUNICI_TEST_TAKEN,PERCENTILE_NATURAL_SCIENCE,PERCENTILE_TOTAL_SCORE,PERCENTILE_ENGLISH,PERCENTILE_CRITICAL_READING,PERCENTILE_MATH,PERCENTILE_SOCIAL_CITIZEN,YEAR_PERIOD_TEST_TAKEN,SCORE_NATURAL_SCIENCE,punt_global,SCORE_ENGLISH,SCORE_CRITICAL_READING,SCORE_MATH,SCORE_SOCIAL_CITIZEN
0,SB11201510000485,311769000921,311769000921,11001,bogota,bogota_d.c.,NaN,NaN,NaN,NaN,NaN,NaN,20151,69,347,90.0,64,72,66
1,SB11201510115564,376250000871,376250000871,76622,valle_cauca,roldanillo,NaN,NaN,NaN,NaN,NaN,NaN,20151,48,239,45.0,49,48,47
2,SB11201510097089,311001105928,311001105928,11001,bogota,bogota_d.c.,NaN,NaN,NaN,NaN,NaN,NaN,20151,34,166,41.0,18,43,35
3,SB11201510115560,376250000871,376250000871,76622,valle_cauca,roldanillo,NaN,NaN,NaN,NaN,NaN,NaN,20151,34,183,42.0,51,29,31
4,SB11201510002784,308001004209,308001004209,8001,atlantico,barranquilla,NaN,NaN,NaN,NaN,NaN,NaN,20151,69,351,85.0,61,82,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5681671,SB11202430031940,111001012963,111001012963,11001,bogota,bogota_d.c.,74.0,64.0,87.0,75.0,10.0,84.0,20242,58,276,66.0,61,36,62
5681672,SB11202430002696,320001006881,320001006881,20001,cesar,valledupar,6.0,23.0,37.0,55.0,20.0,27.0,20242,35,215,46.0,55,41,40
5681673,SB11202430070974,176520002520,176520800222,76520,valle_cauca,palmira,34.0,47.0,66.0,78.0,43.0,34.0,20242,45,251,55.0,62,50,42
5681674,SB11202430586516,305001020558,305001020558,5001,antioquia,medellin,10.0,3.0,8.0,5.0,5.0,3.0,20242,37,165,35.0,35,31,28
5681675,SB11202430450964,141001001593,141001001593,41001,huila,neiva,78.0,63.0,83.0,53.0,25.0,77.0,20242,59,274,64.0,55,43,59

# Write csv

In [86]:
file_path = Path("./saber11_db/data/joined/english/df_result_info_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_result_info.to_csv(file_path, sep=";", index=False)