# Saber 11 test - Cleanliness
    - Author: Santiago Avella. Git hub: https://github.com/TiagoMimi

In [1]:
import pandas as pd
from pathlib import Path
import json
# *Configure pandas to display all columns in DataFrame outputs*
pd.set_option('display.max_columns', None)

## Load the data

In [2]:
# Current working directory
script_path = Path.cwd()

# Find the project folder
project_path = script_path

while project_path.name != "github":
    project_path = project_path.parent

In [ ]:
data_path = project_path / "saber11_db" / "data" / "joined" 

# Read student data types
with open(
    data_path / "data_types_student.json",
    "r",
    encoding="utf-8"
) as file:
    data_type_student = json.load(file)


# List of CSV files
file_list = [
    data_path / "student_info.csv"
]

# DataFrame names
df_names = [
    "df_student_info"]


# Read CSV files using the data types stored in the JSON files
dataframes = {}

for name, file in zip(df_names, file_list):

    # Get table name
    table_name = name.replace("df_", "")

    # Select the corresponding data type dictionary
    if table_name.startswith("teacher_"):
        dtype_mapping = data_type_teacher[table_name]
    else:
        dtype_mapping = data_type_student[table_name]

    # Read CSV
    dataframes[name] = pd.read_csv(
        file,
        sep=";",
        dtype=dtype_mapping,
        low_memory=False
    )


# Assign DataFrames
df_student_info = dataframes["df_student_info"]

### Fuction_to_translate

In [4]:
def translate_values_dictionary(df,column,dict_translation):
    
    df[column] = df[column].replace(dict_translation)

    return df

# STUDENT_INFO

#### student_id

- Id público del inscrito (SB11)
- Public Identifier of the Enrolled Student (SB11)

In [5]:
df_student_info = df_student_info.rename(columns={"student_id":"STUDENT_ID"})

#### estu_agregado => STUDENT_AGGREGATION

- Significado: Indica si el estudiante pertenece a la marca de agregado, la cual determina si será tenido en cuenta en el informe nacional de resultados
- Mean: Indicates whether the student is part of an aggregation group, determining whether their results are included in the national results report.

In [6]:
df_student_info = df_student_info.rename(columns={"estu_agregado":"STUDENT_AGGREGATION"})

In [7]:
dict_translation = {"S":"y",
                    "N":"n"}

In [8]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_AGGREGATION",
                                dict_translation)

In [9]:
df_student_info["STUDENT_AGGREGATION"].value_counts()

STUDENT_AGGREGATION
y    5541849
n     139797
Name: count, dtype: int64

#### school_institution_id

- Código Dane del Establecimiento Educativo 
- Educational Institution DANE ID (DANE (National Administrative Department of Statistics): Colombia's official statistical agency responsible for producing and disseminating statistical information about the country's demographic, social, economic, and educational conditions.)

In [10]:
df_student_info = df_student_info.rename(columns={"school_institution_id":"SCHOOL_INSTITUTION_ID"})

#### school_campus_id

- Código Dane de la Sede
- DANE ID of the Campus (DANE (National Administrative Department of Statistics): Colombia's official statistical agency responsible for producing and disseminating statistical information about the country's demographic, social, economic, and educational conditions.)

In [11]:
df_student_info = df_student_info.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### estu_dedicacioninternet > STUDENT_INTERNET_TIME

- Usualmente, ¿cuánto tiempo al día dedica a navegar en internet? Excluya actividades académicas
- How much time do you usually spend browsing the internet per day? Exclude academic activities

In [12]:
df_student_info = df_student_info.rename(columns={"estu_dedicacioninternet":"STUDENT_INTERNET_TIME"})

In [13]:
dict_translation = {"Entre 1 y 3 horas":"1_3_hours",
                    "Entre 30 y 60 minutos":"30_60_min",
                    "Más de 3 horas":"+3_hours",
                    "30 minutos o menos":"0_30_min",
                    "No Navega Internet":"none_time"}

In [14]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_INTERNET_TIME",
                                dict_translation)

In [15]:
df_student_info["STUDENT_INTERNET_TIME"].value_counts()

STUDENT_INTERNET_TIME
1_3_hours    1322793
30_60_min    1043108
+3_hours      971039
0_30_min      661494
none_time     231014
Name: count, dtype: int64

#### estu_dedicacionlecturadiaria => STUDENT_LECTURE_TIME

- Usualmente, ¿cuánto tiempo al día dedica a leer por entretenimiento?
- How much time do you usually spend reading for pleasure per day?

In [16]:
df_student_info = df_student_info.rename(columns={"estu_dedicacionlecturadiaria":"STUDENT_LECTURE_TIME"})

In [17]:
dict_translation = {"Más de 2 horas":"+2_hours",
                    "Entre 1 y 2 horas":"1_2_hours",
                    "Entre 30 y 60 minutos":"30_60_min",
                    "30 minutos o menos":"0_30_min",
                    "No leo por entretenimiento":"none_time"}

In [18]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_LECTURE_TIME",
                                dict_translation)

In [19]:
df_student_info["STUDENT_LECTURE_TIME"].value_counts()

STUDENT_LECTURE_TIME
0_30_min     1617270
30_60_min    1133398
none_time     861510
1_2_hours     445540
+2_hours      181791
Name: count, dtype: int64

#### estu_depto_reside => STUDENT_DEPART_RESIDENCE

- Departamento de residencia
- Residence Department

In [20]:
df_student_info = df_student_info.rename(columns={"estu_depto_reside":"STUDENT_DEPART_RESIDENCE"})

In [21]:
dict_translation = {
    "BOGOTÁ": "bogota",
    "ANTIOQUIA": "antioquia",
    "VALLE": "valle_cauca",
    "CUNDINAMARCA": "cundinamarca",
    "ATLANTICO": "atlantico",
    "BOLIVAR": "bolivar",
    "SANTANDER": "santander",
    "CORDOBA": "cordoba",
    "NARIÑO": "narino",
    "TOLIMA": "tolima",
    "BOYACA": "boyaca",
    "MAGDALENA": "magdalena",
    "NORTE SANTANDER": "norte_santander",
    "CAUCA": "cauca",
    "HUILA": "huila",
    "CESAR": "cesar",
    "META": "meta",
    "SUCRE": "sucre",
    "CALDAS": "caldas",
    "RISARALDA": "risaralda",
    "BOGOTA": "bogota",
    "LA GUAJIRA": "la_guajira",
    "QUINDIO": "quindio",
    "CASANARE": "casanare",
    "CHOCO": "choco",
    "CAQUETA": "caqueta",
    "PUTUMAYO": "putumayo",
    "ARAUCA": "arauca",
    "GUAVIARE": "guaviare",
    "AMAZONAS": "amazonas",
    "SAN ANDRES": "san_andres",
    "VICHADA": "vichada",
    "VAUPES": "vaupes",
    "GUAINIA": "guainia",
    "EXTRANJERO": "foreign"
}

In [22]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_DEPART_RESIDENCE",
                                dict_translation)

In [23]:
df_student_info["STUDENT_DEPART_RESIDENCE"].value_counts()

STUDENT_DEPART_RESIDENCE
bogota             896183
antioquia          750708
valle_cauca        465210
cundinamarca       371995
atlantico          322819
bolivar            264376
santander          262797
cordoba            208532
narino             175203
tolima             170730
boyaca             167414
magdalena          166167
norte_santander    165034
cauca              149466
huila              139153
cesar              135705
meta               124761
sucre              111195
caldas             108036
risaralda          105869
la_guajira          89749
quindio             64378
casanare            59457
choco               45234
caqueta             42330
putumayo            42317
arauca              32821
guaviare             9908
amazonas             8499
san_andres           6478
vichada              5671
vaupes               3891
guainia              3274
foreign               221
Name: count, dtype: int64

#### estu_discapacidad => STUDENT_DISABILITY

- Indica si el estudiante presenta alguna condición de discapacidad
- Indicates whether the student has a disability condition.

In [24]:
df_student_info = df_student_info.rename(columns={"estu_discapacidad":"STUDENT_DISABILITY"})

In [25]:
dict_translation = {"S":"y",
                    "N":"n"}

In [26]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_DISABILITY",
                                dict_translation)

In [27]:
df_student_info["STUDENT_DISABILITY"].value_counts()

STUDENT_DISABILITY
n    5063438
y      45293
Name: count, dtype: int64

#### estu_estudiante => Delete

In [28]:
df_student_info["estu_estudiante"].value_counts()

estu_estudiante
ESTUDIANTE    5681676
Name: count, dtype: int64

In [29]:
df_student_info = df_student_info.drop(columns="estu_estudiante")

#### estu_etnia => DELETE

In [30]:
df_student_info = df_student_info.rename(columns={"estu_etnia":"STUDENT_ETHNICITY"})

In [31]:
df_student_info = df_student_info.drop(columns="STUDENT_ETHNICITY")

In [32]:
df_student_info

,STUDENT_ID,STUDENT_AGGREGATION,SCHOOL_INSTITUTION_ID,SCHOOL_CAMPUS_ID,STUDENT_INTERNET_TIME,STUDENT_LECTURE_TIME,STUDENT_DEPART_RESIDENCE,STUDENT_DISABILITY,estu_fechanacimiento,estu_generacione,estu_genero,estu_grado,estu_grupoetnia,estu_horassemanatrabaja,estu_nacionalidad,estu_pilopaga,estu_privado_libertad,estu_repite,estu_tieneetnia,estu_tipodocumento,estu_tiporemuneracion,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_mcpio_reside,estu_pais_reside
0,SB11201510000485,y,311769000921,311769000921,NaN,NaN,bogota,NaN,25/09/1995,NaN,M,11.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,CC,NaN,11,11001,BOGOTÁ D.C.,COLOMBIA
1,SB11201510115564,y,376250000871,376250000871,NaN,NaN,valle_cauca,NaN,19/06/1998,NaN,F,26.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,TI,NaN,76,76250,EL DOVIO,COLOMBIA
2,SB11201510097089,y,311001105928,311001105928,NaN,NaN,bogota,NaN,09/12/1997,NaN,M,26.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,TI,NaN,11,11001,BOGOTÁ D.C.,COLOMBIA
3,SB11201510115560,y,376250000871,376250000871,NaN,NaN,valle_cauca,NaN,10/02/1997,NaN,F,26.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,CC,NaN,76,76622,ROLDANILLO,COLOMBIA
4,SB11201510002784,y,308001004209,308001004209,NaN,NaN,atlantico,NaN,13/01/1997,NaN,M,11.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,TI,NaN,8,8001,BARRANQUILLA,COLOMBIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5681671,SB11202430031940,y,111001012963,111001012963,1_3_hours,0_30_min,bogota,n,09/04/2007,NaN,F,11.0,NINGUNO,Menos de 10 horas,COLOMBIA,NaN,N,0.0,NaN,TI,"Si, en efectivo",11,11001,BOGOTÁ D.C.,COLOMBIA
5681672,SB11202430002696,y,320001006881,320001006881,1_3_hours,none_time,cesar,n,06/02/2007,NaN,M,11.0,NINGUNO,NaN,COLOMBIA,NaN,N,0.0,NaN,TI,NaN,20,20001,VALLEDUPAR,COLOMBIA
5681673,SB11202430070974,y,176520002520,176520800222,1_3_hours,0_30_min,valle_cauca,n,24/09/2006,NaN,F,11.0,NINGUNO,0,COLOMBIA,NaN,N,0.0,NaN,TI,No,76,76520,PALMIRA,COLOMBIA
5681674,SB11202430586516,y,305001020558,305001020558,+3_hours,none_time,antioquia,n,08/12/2006,NaN,F,26.0,NINGUNO,0,COLOMBIA,NaN,N,0.0,NaN,TI,No,5,5001,MEDELLÍN,COLOMBIA
5681675,SB11202430450964,y,141001001593,141001001593,30_60_min,none_time,huila,n,25/08/2007,NaN,F,11.0,NINGUNO,0,COLOMBIA,NaN,N,0.0,NaN,TI,No,41,41001,NEIVA,COLOMBIA

#### estu_grupoetnia => STUDENT_ETHNICITY

- ¿Pertenece usted a un grupo étnico minoritario? 
- Do you identify as a member of an ethnic minority group?

In [33]:
df_student_info = df_student_info.rename(columns={"estu_grupoetnia":"STUDENT_ETHNICITY"})

In [34]:
dict_translation ={
    "NINGUNO": "none",
    "NEGRO AFRODESCENDIENTE": "black_afro_descendant",
    "INDIGENA": "indigenous",
    "RAIZAL": "raizal",
    "PALENQUERO": "palenquero",
    "COMUNIDAD ROM": "roma_community"
}

In [35]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_ETHNICITY",
                                dict_translation)

In [36]:
df_student_info["STUDENT_ETHNICITY"].value_counts()

STUDENT_ETHNICITY
none                     1046573
black_afro_descendant      53880
indigenous                 36918
raizal                       714
palenquero                   167
roma_community                32
Name: count, dtype: int64

#### estu_fechanacimiento => STUDENT_DATE_BIRTH

- Fecha de nacimiento
- Date of birth

In [37]:
df_student_info = df_student_info.rename(columns={"estu_fechanacimiento":"STUDENT_DATE_BIRTH"})

#### estu_generacione => STUDENT_EGENERATION

- Identifica si el evaluado cumple con los requisitos necesarios para ser beneficiario del programa Generación E
- Indicates whether the student meets the eligibility criteria for the Generación E Program

In [38]:
df_student_info = df_student_info.rename(columns={"estu_generacione":"STUDENT_EGENERATION"})

In [39]:
dict_translation = {"GENERACION E - GRATUIDAD":"y",
                    "GENERACION E - EXCELENCIA NACIONAL":"y",
                    "GENERACION E - EXCELENCIA DEPARTAMENTAL":"y",
                    "NO":"n"}

In [40]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_EGENERATION",
                                dict_translation)

In [41]:
df_student_info["STUDENT_EGENERATION"].value_counts()

STUDENT_EGENERATION
n    1101410
y    1099183
Name: count, dtype: int64

#### estu_genero => STUDENT_GENDER

- Género
- Gender

In [42]:
df_student_info = df_student_info.rename(columns={"estu_genero":"STUDENT_GENDER"})

In [43]:
df_student_info["STUDENT_GENDER"].value_counts()

STUDENT_GENDER
F    3069589
M    2608959
Name: count, dtype: int64

#### estu_grado => STUDENT_GRADE

- Grado en el que se encuentra matriculado el estudiante en el SIMAT al momento de presentar la prueba como ESTUDIANTE
- Indicates the grade in which the student was enrolled in the Integrated Enrollment System (SIMAT) at the time of taking the assessment as a student (SIMAT = Integrated Enrollment System, administrado por el Colombian Ministry of National Education).

In [44]:
df_student_info = df_student_info.rename(columns={"estu_grado":"STUDENT_GRADE"})

In [45]:
df_student_info["STUDENT_GRADE"].value_counts()

STUDENT_GRADE
11.0       4926593
26.0        752767
25.0          1399
12.0           697
10.0           104
20234.0         20
27.0             1
Name: count, dtype: int64

#### estu_pilopaga => STUDENT_PILOPAGA

In [46]:
df_student_info = df_student_info.rename(columns={"estu_pilopaga":"STUDENT_PILOPAGA"})

In [47]:
dict_translation = {"SER PILO PAGA - CREDITO CONDONABLE":"y",
                    "SER PILO PAGA PAZCIFICO - CREDITO CONDONABLE":"y",
                    "SER PILO PAGA - ETNIA":"y",
                    "SER PILO PAGA MOCOA - CREDITO CONDONABLE":"y",
                    "NO":"n",
                    "SI": "y"}

In [48]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_PILOPAGA",
                                dict_translation)

In [49]:
df_student_info["STUDENT_PILOPAGA"].value_counts()

STUDENT_PILOPAGA
n    1705491
y      32849
Name: count, dtype: int64

####  estu_horassemanatrabaja => STUDENT_HOURS_WORKING

- ¿Cuántas horas trabajó usted durante la semana pasada?
- How many hours did you work during the previous week?

In [50]:
df_student_info = df_student_info.rename(columns={"estu_horassemanatrabaja":"STUDENT_HOURS_WORKING"})

In [51]:
dict_translation = {"Menos de 10 horas":"0_10_hours",
                    "Entre 11 y 20 horas":"11_20_hours",
                    "Entre 21 y 30 horas":"21_30_hours",
                    "Más de 30 horas":"30+_hours",
                    "0":"none_time"}

In [52]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_HOURS_WORKING",
                                dict_translation)

In [53]:
df_student_info["STUDENT_HOURS_WORKING"].value_counts()

STUDENT_HOURS_WORKING
none_time      2752767
0_10_hours      883989
11_20_hours     389908
30+_hours       169814
21_30_hours     145683
Name: count, dtype: int64

#### estu_nacionalidad => STUDENT_NACIONALITY

- Nacionalidad del estudiante
- Student nacionality

In [54]:
df_student_info = df_student_info.rename(columns={"estu_nacionalidad":"STUDENT_NACIONALITY"})

In [55]:
nationality_dict = {
    "COLOMBIA": "colombia",
    "VENEZUELA": "venezuela"
}

df_student_info["STUDENT_NACIONALITY"] = (df_student_info["STUDENT_NACIONALITY"].map(nationality_dict).fillna("other"))

In [56]:
print(df_student_info["STUDENT_NACIONALITY"].value_counts().to_string())

STUDENT_NACIONALITY
colombia     5643013
venezuela      35608
other           3055

#### estu_privado_libertad => STUDENT_DEPRIVED_LIBERTY

- ¿Se encuentra privado de la libertad?
- Are you currently deprived of liberty?

In [57]:
df_student_info = df_student_info.rename(columns={"estu_privado_libertad":"STUDENT_DEPRIVED_LIBERTY"})

In [58]:
dict_translation = {"S":"y",
                    "N":"n"}

In [59]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_DEPRIVED_LIBERTY",
                                dict_translation)

In [60]:
df_student_info["STUDENT_DEPRIVED_LIBERTY"].value_counts()

STUDENT_DEPRIVED_LIBERTY
n    5680086
y       1577
Name: count, dtype: int64

####  estu_repite => STUDENT_REPEAT_TEST

- Código único del estudiante en repitencia de la prueba, permitiendo rastrear si el mismo estudiante ha presentado la prueba en más de un periodo.
- Unique identifier assigned to the student for repeated test-taking, allowing the same student to be tracked across multiple assessment periods.

In [61]:
df_student_info = df_student_info.rename(columns={"estu_repite":"STUDENT_REPEAT_TEST"})

In [62]:
df_student_info["STUDENT_REPEAT_TEST"] = (df_student_info["STUDENT_REPEAT_TEST"].map({0:"n"}).fillna("y"))

In [63]:
df_student_info["STUDENT_REPEAT_TEST"].value_counts()

STUDENT_REPEAT_TEST
n    4831476
y     850200
Name: count, dtype: int64

#### estu_tipodocumento => DELETE

In [64]:
df_student_info = df_student_info.drop(columns="estu_tipodocumento")

#### estu_tieneetnia => STUDENT_ETHNICITY_V2

- ¿Pertenece usted a un grupo étnico minoritario?
- “Do you belong to an ethnic minority group?”

In [65]:
df_student_info = df_student_info.rename(columns={"estu_tieneetnia":"STUDENT_ETHNICITY_V2"})

In [66]:
dict_translation = {"Si":"y",
                    "No":"n",
                    "S": "y"}

In [67]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_ETHNICITY_V2",
                                dict_translation)

In [68]:
df_student_info["STUDENT_ETHNICITY_V2"].value_counts()

STUDENT_ETHNICITY_V2
n    4207749
y     311502
Name: count, dtype: int64

#### estu_tiporemuneracion => STUDENT_COMPENSATION_TYPE

In [69]:
df_student_info = df_student_info.rename(columns={"estu_tiporemuneracion":"STUDENT_COMPENSATION_TYPE"})

In [70]:
dict_translation = {"Si, en efectivo":"cash",
                    "Si, en especie":"kind",
                    "Si, en efectivo y especie":"cash_kind",
                    "No":"n"}

In [71]:
df_student_info = translate_values_dictionary(df_student_info,
                                "STUDENT_COMPENSATION_TYPE",
                                dict_translation)

In [72]:
df_student_info["STUDENT_COMPENSATION_TYPE"].value_counts()

STUDENT_COMPENSATION_TYPE
n            2995849
cash         1188457
kind           80213
cash_kind      68733
Name: count, dtype: int64

#### estu_mcpio_reside	=> STUDENT_MUNICIPALITY_RESIDENCE

In [73]:
df_student_info = df_student_info.rename(columns={"estu_mcpio_reside":"STUDENT_MUNICIPALITY_RESIDENCE"})

In [74]:
import unicodedata

df_student_info["STUDENT_MUNICIPALITY_RESIDENCE"] = (
    df_student_info["STUDENT_MUNICIPALITY_RESIDENCE"]
    .apply(lambda x: ''.join(
        c for c in unicodedata.normalize('NFD', str(x))
        if unicodedata.category(c) != 'Mn'
    ).lower().replace(' ', '_'))
)

#### estu_pais_reside =>  STUDENT_COUNTRY_RESIDENCE

In [75]:
df_student_info = df_student_info.rename(columns={"estu_pais_reside":"STUDENT_COUNTRY_RESIDENCE"})

In [76]:
import unicodedata

df_student_info["STUDENT_COUNTRY_RESIDENCE"] = (
    df_student_info["STUDENT_COUNTRY_RESIDENCE"]
    .apply(lambda x: ''.join(
        c for c in unicodedata.normalize('NFD', str(x))
        if unicodedata.category(c) != 'Mn'
    ).lower().replace(' ', '_'))
)

In [77]:
df_student_info

,STUDENT_ID,STUDENT_AGGREGATION,SCHOOL_INSTITUTION_ID,SCHOOL_CAMPUS_ID,STUDENT_INTERNET_TIME,STUDENT_LECTURE_TIME,STUDENT_DEPART_RESIDENCE,STUDENT_DISABILITY,STUDENT_DATE_BIRTH,STUDENT_EGENERATION,STUDENT_GENDER,STUDENT_GRADE,STUDENT_ETHNICITY,STUDENT_HOURS_WORKING,STUDENT_NACIONALITY,STUDENT_PILOPAGA,STUDENT_DEPRIVED_LIBERTY,STUDENT_REPEAT_TEST,STUDENT_ETHNICITY_V2,STUDENT_COMPENSATION_TYPE,estu_cod_reside_depto,estu_cod_reside_mcpio,STUDENT_MUNICIPALITY_RESIDENCE,STUDENT_COUNTRY_RESIDENCE
0,SB11201510000485,y,311769000921,311769000921,NaN,NaN,bogota,NaN,25/09/1995,NaN,M,11.0,NaN,NaN,colombia,n,n,y,NaN,NaN,11,11001,bogota_d.c.,colombia
1,SB11201510115564,y,376250000871,376250000871,NaN,NaN,valle_cauca,NaN,19/06/1998,NaN,F,26.0,NaN,NaN,colombia,n,n,y,NaN,NaN,76,76250,el_dovio,colombia
2,SB11201510097089,y,311001105928,311001105928,NaN,NaN,bogota,NaN,09/12/1997,NaN,M,26.0,NaN,NaN,colombia,n,n,y,NaN,NaN,11,11001,bogota_d.c.,colombia
3,SB11201510115560,y,376250000871,376250000871,NaN,NaN,valle_cauca,NaN,10/02/1997,NaN,F,26.0,NaN,NaN,colombia,n,n,y,NaN,NaN,76,76622,roldanillo,colombia
4,SB11201510002784,y,308001004209,308001004209,NaN,NaN,atlantico,NaN,13/01/1997,NaN,M,11.0,NaN,NaN,colombia,n,n,y,NaN,NaN,8,8001,barranquilla,colombia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5681671,SB11202430031940,y,111001012963,111001012963,1_3_hours,0_30_min,bogota,n,09/04/2007,NaN,F,11.0,none,0_10_hours,colombia,NaN,n,n,NaN,cash,11,11001,bogota_d.c.,colombia
5681672,SB11202430002696,y,320001006881,320001006881,1_3_hours,none_time,cesar,n,06/02/2007,NaN,M,11.0,none,NaN,colombia,NaN,n,n,NaN,NaN,20,20001,valledupar,colombia
5681673,SB11202430070974,y,176520002520,176520800222,1_3_hours,0_30_min,valle_cauca,n,24/09/2006,NaN,F,11.0,none,none_time,colombia,NaN,n,n,NaN,n,76,76520,palmira,colombia
5681674,SB11202430586516,y,305001020558,305001020558,+3_hours,none_time,antioquia,n,08/12/2006,NaN,F,26.0,none,none_time,colombia,NaN,n,n,NaN,n,5,5001,medellin,colombia
5681675,SB11202430450964,y,141001001593,141001001593,30_60_min,none_time,huila,n,25/08/2007,NaN,F,11.0,none,none_time,colombia,NaN,n,n,NaN,n,41,41001,neiva,colombia

# Write csv

In [83]:
file_path = Path("./saber11_db/data/joined/english/df_student_info_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_student_info.to_csv(file_path, sep=";", index=False)